#define mag_xx(a,b) class _xx_##a {magazine = a; count = b;}
#define weap_xx(a,b) class _xx_##a {weapon = a; count = b;}
#define item_xx(a,b) class _xx_##a {name = a; count = b;}

class CfgPatches {
	class unit_config {
		units[] = {"B_SEA_Base_Camo",
		"B_SEA_Base_C_od",
		"B_SEA_Base_Ctan",
		"B_SEA_Base_lite",
		"B_SEA_AAR",
		"B_SEA_AR",
		"B_SEA_CE",
		"B_SEA_CLS",
		"B_SEA_DEMO",
		"B_SEA_GREN",
		"B_SEA_HG",
		"B_SEA_MARK",
		"B_SEA_MERC",
		"B_SEA_AT",
		"B_SEA_MINE",
		"B_SEA_MECH",
		"B_SEA_RECN",
		"B_SEA_SS",
		"B_SEA_SL",
		"B_SEA_TL",//blufor ends here
		"I_SEA_Base_Camo",
		"I_SEA_Base_C_od",
		"I_SEA_Base_Ctan",
		"I_SEA_Base_lite",
		"I_SEA_AAR",
		"I_SEA_AR",
		"I_SEA_CE",
		"I_SEA_CLS",
		"I_SEA_DEMO",
		"I_SEA_GREN",
		"I_SEA_HG",
		"I_SEA_MARK",
		"I_SEA_MERC",
		"I_SEA_AT",
		"I_SEA_MINE",
		"I_SEA_MECH",
		"I_SEA_RECN",
		"I_SEA_SS",
		"I_SEA_SL",
		"I_SEA_TL",//indfor ends here
		"O_SEA_Base_Camo",
		"O_SEA_Base_C_od",
		"O_SEA_Base_Ctan",
		"O_SEA_Base_lite",
		"O_SEA_AAR",
		"O_SEA_AR",
		"O_SEA_CE",
		"O_SEA_CLS",
		"O_SEA_DEMO",
		"O_SEA_GREN",
		"O_SEA_HG",
		"O_SEA_MARK",
		"O_SEA_MERC",
		"O_SEA_AT",
		"O_SEA_MINE",
		"O_SEA_MECH",
		"O_SEA_RECN",
		"O_SEA_SS",
		"O_SEA_SL",
		"O_SEA_TL",
		//Transitioning to PMC Faction
		"B_PMC_Base_C_od",
		"B_PMC_Base_Ctan",
		"B_PMC_Base_lite",
		"B_PMC_AAR",
		"B_PMC_AR",
		"B_PMC_CE",
		"B_PMC_CLS",
		"B_PMC_DEMO",
		"B_PMC_GREN",
		"B_PMC_HG",
		"B_PMC_MARK",
		"B_PMC_MERC",
		"B_PMC_AT",
		"B_PMC_MINE",
		"B_PMC_MECH",
		"B_PMC_RECN",
		"B_PMC_SS",
		"B_PMC_SL",
		"B_PMC_TL",//blufor ends here
		"I_PMC_Base_Camo",
		"I_PMC_Base_C_od",
		"I_PMC_Base_Ctan",
		"I_PMC_Base_lite",
		"I_PMC_AAR",
		"I_PMC_AR",
		"I_PMC_CE",
		"I_PMC_CLS",
		"I_PMC_DEMO",
		"I_PMC_GREN",
		"I_PMC_HG",
		"I_PMC_MARK",
		"I_PMC_MERC",
		"I_PMC_AT",
		"I_PMC_MINE",
		"I_PMC_MECH",
		"I_PMC_RECN",
		"I_PMC_SS",
		"I_PMC_SL",
		"I_PMC_TL",//indfor ends here
		"O_PMC_Base_Camo",
		"O_PMC_Base_C_od",
		"O_PMC_Base_Ctan",
		"O_PMC_Base_lite",
		"O_PMC_AAR",
		"O_PMC_AR",
		"O_PMC_CE",
		"O_PMC_CLS",
		"O_PMC_DEMO",
		"O_PMC_GREN",
		"O_PMC_HG",
		"O_PMC_MARK",
		"O_PMC_MERC",
		"O_PMC_AT",
		"O_PMC_MINE",
		"O_PMC_MECH",
		"O_PMC_RECN",
		"O_PMC_SS",
		"O_PMC_SL",
		"O_PMC_TL",
		//Merc/PMC Assets
		"VSM_OGA_OD_Backpack_Kitbag_AAR",
		"VSM_OGA_OD_Backpack_Kitbag_ENG",
		"VSM_OGA_OD_Backpack_Compact_CLS",
		"VSM_OGA_OD_Backpack_Kitbag_DMO",
		"VSM_OGA_OD_Backpack_Kitbag_AT",
		"VSM_OGA_OD_Backpack_Kitbag_MNE",
		"VSM_OGA_OD_Backpack_Compact_REP"
		//PMC-Specific Assets
		};
		weapons[] = {"VSM_M81_BDU_Camo_INDFOR",
		"VSM_M81_BDU_C_od_INDFOR",
		"VSM_M81_BDU_Ctan_INDFOR",
		"hlc_rifle_g3ka4_SightLight",
		"hlc_rifle_g3ka4_3XSightLight",
		"hlc_rifle_g3ka4_SightLightSnds",
		"hlc_rifle_g3ka4_LMG",
		"HLC_Rifle_g3ka4_GL_SightLight",
		"HLC_Rifle_g3ka4_GL_3XSightLight",
		"hlc_rifle_g3sg1ris_Kahlia",
		"hlc_rifle_PSG1A1_RIS_Kahlia"
		};
		requiredVersion = 0.1;
		requiredAddons[] = {"A3_Characters_F_BLUFOR","A3_Characters_F_Exp","VSM_M81_Config"};
	};
};